//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModernArtEntities : DbContext
    {
        public ModernArtEntities()
            : base("name=ModernArtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Выставки> Выставки { get; set; }
        public virtual DbSet<Выставки_Деятели> Выставки_Деятели { get; set; }
        public virtual DbSet<Деятели> Деятели { get; set; }
        public virtual DbSet<Место_проведения> Место_проведения { get; set; }
        public virtual DbSet<Отзывы> Отзывы { get; set; }
        public virtual DbSet<Посетители> Посетители { get; set; }
        public virtual DbSet<Посетители_Отзывы> Посетители_Отзывы { get; set; }
        public virtual DbSet<Продажи> Продажи { get; set; }
        public virtual DbSet<Экспонат> Экспонат { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Приглашения> Приглашения { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Выставки_Посетители> Выставки_Посетители { get; set; }
        public virtual DbSet<ПокупкиБилетов> ПокупкиБилетов { get; set; }
    }
}
