//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Выставки_Деятели
    {
        public int ID_Выставки { get; set; }
        public int ID_Деятели { get; set; }
        public Nullable<System.DateTime> ДатаРегистрации { get; set; }
    
        public virtual Выставки Выставки { get; set; }
        public virtual Деятели Деятели { get; set; }
    }
}
