//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отзывы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Отзывы()
        {
            this.Посетители_Отзывы = new HashSet<Посетители_Отзывы>();
        }
    
        public int ID_Отзывы { get; set; }
        public string Текст { get; set; }
        public Nullable<int> ID_Выставки { get; set; }
    
        public virtual Выставки Выставки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Посетители_Отзывы> Посетители_Отзывы { get; set; }
    }
}
