//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Посетители_Отзывы
    {
        public int ID_Посетители { get; set; }
        public int ID_Отзывы { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
    
        public virtual Отзывы Отзывы { get; set; }
        public virtual Посетители Посетители { get; set; }
    }
}
