//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Приглашения
    {
        public int ID_Приглашения { get; set; }
        public int ID_Выставки { get; set; }
        public int ID_Деятели { get; set; }
        public string Статус { get; set; }
        public Nullable<System.DateTime> Дата_приглашения { get; set; }
    
        public virtual Выставки Выставки { get; set; }
        public virtual Деятели Деятели { get; set; }
    }
}
