//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Экспонат
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Экспонат()
        {
            this.Продажи = new HashSet<Продажи>();
        }
    
        public int ID_Экспонат { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public Nullable<int> Год_создания { get; set; }
        public string Тип_экспоната { get; set; }
        public Nullable<int> ID_Выставки { get; set; }
        public Nullable<int> ID_Деятели { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Выставки Выставки { get; set; }
        public virtual Деятели Деятели { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продажи> Продажи { get; set; }
    }
}
